name: Publish nopalm to npm registry

on:
  push:
    branches:
      - main

jobs:
  publish_package:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      # Install all dependencies (including devDependencies for lint/test/build)
      - name: Install dependencies
        run: yarn install

      # Run linting
      - name: Run lint
        run: yarn lint

      # Run tests
      - name: Run tests
        run: yarn test

      # Build production version of react client
      - name: Build client
        run: yarn build-client

      # Verify NPM_TOKEN
      - name: Verify NPM_TOKEN
        run: |
          curl -H "Authorization: Bearer $NPM_TOKEN" https://registry.npmjs.org/-/whoami

      # Semantic release step: Automatically determine the version and release
      - name: Semantic release the package
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
